# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 10 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          config_output: json

          # Options
          user: fraasi
          # template: classic
          # base: header, activity, community, repositories, metadata
          config_timezone: Europe/Helsinki

          plugin_achievements: yes
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic

          plugin_languages: yes
          plugin_languages_other: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_categories: markup, programming
          plugin_languages_threshold: 0%
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 21
          plugin_traffic: yes

      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          user: fraasi

          # Options
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Helsinki

          plugin_achievements: yes
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic

          plugin_languages: yes
          plugin_languages_other: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_categories: markup, programming
          plugin_languages_threshold: 0%
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 21
          plugin_traffic: yes
