on:
  schedule:
    - cron: '10 10 * * *'
  push:
    branches:
      - master
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Update README.md
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        npm ci
        node ./dist/index.js
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email fraasi@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git push
        fi
